name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - infra/4889-IB
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests-wp-4-9-gutenberg.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '/*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - '/php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests-wp-4-9-gutenberg.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '/*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - '/php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: e2e-tests-wp-4-9-gutenberg-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests-wp-4-9-gutenberg:
    name: E2E (WordPress 4.9, Gutenberg 4.9)

    env:
      WP_VERSION: 4.9.16
      GUTENBERG_VERSION: 4.9.0

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Cache ~/.npm
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache node_modules
        id: cache-npm-install
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-install
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.cache-npm-install.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache dist
        id: cache-dist
        uses: actions/cache@v2
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ env.cache-name }}-${{ hashFiles('assets/**/*') }}

      - name: Build
        if: steps.cache-dist.outputs.cache-hit != 'true'
        run: npm run build:test

      # E2E tests use a dedicated container, this is just for Composer.
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.x'
          tools: composer:2.1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Install
        run: composer install --no-interaction --no-progress --no-dev

      - name: Unzip AMP plugin
        run: cd plugins/amp && unzip amp-prod.zip

      - name: Start environment
        run: npm run env:start

      - name: check amp plugin files
        run: |
          docker exec googlesitekit-e2e_wordpress_1 wc -l wp-content/plugins/amp/assets/js/amp-settings.js wp-content/plugins/amp/vendor/autoload.php
          docker exec googlesitekit-e2e_wordpress_1 ls -l wp-content/plugins/amp/assets/js/amp-settings.js wp-content/plugins/amp/vendor/autoload.php

      - name: Run the tests
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: e2e-screenshots
          path: tests/e2e/screenshots
